language: python
services:
  - postgresql
python:
  - 2.7
before_install:
  - sudo apt-get install -qq python-tox
before_script:
  - psql -c 'create database capomastro;' -U postgres
  - sed -i -e 's/getpass\.getuser()/\"postgres\"/g' capomastro/local_settings.py
script:
  - tox
