language: python
services:
  - postgresql
python:
  - 2.7
before_install:
  - sudo pip install tox
before_script:
  - psql -c 'create database capomastro;' -U postgres
  - sed -i -e 's/getpass\.getuser()/\"postgres\"/g' capomastro/local_settings.py
script:
  - /usr/local/bin/tox
