#!/bin/sh

set -e

NAME=capomastro

if ! getent group | grep -q ${NAME}; then
	groupadd --system -f ${NAME}
fi

if ! getent passwd | grep -q ${NAME}; then
	useradd --system -g ${NAME} ${NAME}
fi

chown ${NAME}:${NAME} /var/log/${NAME}

chmod g+w /var/log/${NAME}

#DEBHELPER#

exit 0
